# Fly.io 配置 - TradesPro 后端 API
# 文档: https://fly.io/docs/reference/configuration/

app = "tradespro-api"
primary_region = "sea"  # Seattle, 或改为 "yyz" (Toronto)

# 使用 Dockerfile 构建
[build]
  dockerfile = "Dockerfile"

# 环境变量（非敏感信息）
# 敏感信息使用 fly secrets set
[env]
  PORT = "8000"
  ENVIRONMENT = "production"

# HTTP 服务配置
[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false  # 永不休眠
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

# VM 资源配置
[[vm]]
  cpu_kind = "shared"  # 共享 CPU（最便宜）
  cpus = 1
  memory_mb = 256  # 256MB RAM = $1.94/月

# 健康检查
[[services.http_checks]]
  interval = "30s"
  timeout = "5s"
  grace_period = "10s"
  method = "GET"
  path = "/health"
  protocol = "http"

# Secrets（敏感信息）需要通过命令设置：
# fly secrets set SECRET_KEY="your-secret-key" -a tradespro-api
# fly secrets set ALGORITHM="HS256" -a tradespro-api
# fly secrets set ACCESS_TOKEN_EXPIRE_MINUTES="30" -a tradespro-api
# fly secrets set CORS_ORIGINS="https://tradespro-frontend.fly.dev" -a tradespro-api
# fly secrets set DEBUG="false" -a tradespro-api

# 自动缩放（可选）
# [http_service.concurrency]
#   type = "requests"
#   soft_limit = 200
#   hard_limit = 250

# 如需数据库，可以连接 Fly PostgreSQL
# [[statics]]
#   guest_path = "/app/static"
#   url_prefix = "/static"

